import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthRouter from "./authRouter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Payment App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthRouter>
        <body className={inter.className}>{children}</body>
      </AuthRouter>
    </html>
  );
}
